# Generated by Django 5.1.4 on 2025-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
