# Generated by Django 5.1.4 on 2025-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0002_lead_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
