# Generated by Django 5.1.4 on 2025-02-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0003_alter_lead_address_alter_lead_email_alter_lead_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
    ]
