# Generated by Django 5.1.4 on 2025-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0004_remove_lead_lead_id_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
