# Generated by Django 5.1.4 on 2025-02-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='items',
            new_name='parts',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], max_length=50),
        ),
    ]
