# Generated by Django 5.1.4 on 2025-01-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0007_alter_invoice_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='original_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='lead_to_invoice.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
